"""
This type stub file was generated by pyright.
"""

import logging
import types
import sys
from typing import Any
from .schema import create_combined_view, init_db
from .conn import get_connection
from .articles import article_exists, enrich_articles_from_crossref, ensure_article_row, get_article_by_title, get_article_metadata, get_missing_crossref_dois, update_article_crossref, upsert_article
from .publications import sync_publications_from_feeds, upsert_publication
from .headlines import save_headlines, save_news_items, upsert_news_item
from .maintenance_sync import sync_articles_from_items
from .maintenance_journal import fetch_latest_journal_works
from .maintenance_vacuum import vacuum_db
from .maintenance_log import log_maintenance_run
from .maintenance_cleanup import cleanup_empty_articles, cleanup_filtered_titles
from .maintenance_rematch import rematch_publication_dois
from .maintenance_remove import remove_feed_articles
from .migrations import migrate_add_items_url_hash, migrate_db

"""ednews.db package facade.

Thin re-exports of connection, schema, CRUD helpers, and maintenance utilities
split across focused modules. Maintains backward compatibility for
`from ednews import db` and `from ednews.db import manage_db`.
"""
logger = ...
mod_name = ...
if mod_name not in sys.modules:
    manage_mod = ...
__all__ = ["get_connection", "init_db", "create_combined_view", "migrate_db", "migrate_add_items_url_hash", "sync_publications_from_feeds", "sync_articles_from_items", "fetch_latest_journal_works", "vacuum_db", "log_maintenance_run", "cleanup_empty_articles", "cleanup_filtered_titles", "rematch_publication_dois", "remove_feed_articles", "upsert_article", "ensure_article_row", "article_exists", "get_article_metadata", "get_article_by_title", "enrich_articles_from_crossref", "get_missing_crossref_dois", "update_article_crossref", "upsert_publication", "upsert_news_item", "save_headlines", "save_news_items"]

# Provide a loose-typed name for the historical manage_db module so attribute
# access like `manage_db.migrate_db` is accepted by static analyzers.
manage_db: Any
