"""
This type stub file was generated by pyright.
"""

import sqlite3

"""Article-related DB helpers split from ednews.db.__init__."""
logger = ...
def upsert_article(conn, doi: str | None, title: str | None, authors: str | None, abstract: str | None, feed_id: str | None = ..., publication_id: str | None = ..., issn: str | None = ..., fetched_at: str | None = ..., published: str | None = ...): # -> Literal[False]:
    ...

def ensure_article_row(conn, doi: str, title: str | None = ..., authors: str | None = ..., abstract: str | None = ..., feed_id: str | None = ..., publication_id: str | None = ..., issn: str | None = ...) -> int | None:
    ...

def article_exists(conn: sqlite3.Connection, doi: str) -> bool:
    ...

def get_article_metadata(conn: sqlite3.Connection, doi: str) -> dict | None:
    ...

def get_article_by_title(conn: sqlite3.Connection, title: str) -> dict | None:
    ...

def enrich_articles_from_crossref(conn, fetcher, batch_size: int = ..., delay: float = ..., return_ids: bool = ...): # -> list[int] | int:
    ...

def get_missing_crossref_dois(conn: sqlite3.Connection, limit: int = ..., offset: int = ...) -> list:
    ...

def update_article_crossref(conn: sqlite3.Connection, doi: str, authors: str | None = ..., abstract: str | None = ..., raw: str | None = ..., published: str | None = ...) -> bool:
    ...

__all__ = ["upsert_article", "ensure_article_row", "article_exists", "get_article_metadata", "get_article_by_title", "enrich_articles_from_crossref", "get_missing_crossref_dois", "update_article_crossref"]
