"""
This type stub file was generated by pyright.
"""

"""Connection helpers for ednews.db"""
logger = ...
def get_connection(path: str | None = ...): # -> Connection:
    """Return a SQLite connection.
    If `path` is provided a connection to that file path is opened; otherwise
    an in-memory connection is returned. Exceptions are propagated after being
    logged.
    """
    ...

__all__ = ["get_connection"]
