"""
This type stub file was generated by pyright.
"""

import sqlite3

"""Headlines/news helpers split from ednews.db.__init__."""
logger = ...
def upsert_news_item(conn: sqlite3.Connection, source: str, title: str | None, text: str | None, link: str | None, published: str | None = ..., first_seen: str | None = ...) -> int | bool:
    ...

def save_headlines(conn: sqlite3.Connection, source: str, items: list[dict]) -> int:
    ...

def save_news_items(conn: sqlite3.Connection, source: str, items: list[dict]) -> int:
    ...

__all__ = ["upsert_news_item", "save_headlines", "save_news_items"]
