"""
This type stub file was generated by pyright.
"""

import sqlite3

"""Cleanup helpers extracted from maintenance.py."""
logger = ...
def cleanup_empty_articles(conn: sqlite3.Connection, older_than_days: int | None = ...) -> int:
    ...

def cleanup_filtered_titles(conn: sqlite3.Connection, filters: list | None = ..., dry_run: bool = ...) -> int:
    ...

__all__ = ["cleanup_empty_articles", "cleanup_filtered_titles"]
