"""
This type stub file was generated by pyright.
"""

import sqlite3

"""Sync helpers (publications and articles) extracted from maintenance.py."""
logger = ...
def sync_publications_from_feeds(conn, feeds_list) -> int:
    ...

def sync_articles_from_items(conn: sqlite3.Connection, feed_keys: list | None = ..., publication_id: str | None = ..., dry_run: bool = ...) -> dict:
    ...

__all__ = ["sync_publications_from_feeds", "sync_articles_from_items"]
