"""
This type stub file was generated by pyright.
"""

import sqlite3

"""Vacuum helper extracted from maintenance.py."""
logger = ...
def vacuum_db(conn: sqlite3.Connection): # -> bool:
    ...

__all__ = ["vacuum_db"]
