"""
This type stub file was generated by pyright.
"""

import sqlite3

"""Logging helper for maintenance runs (extracted from maintenance.py)."""
logger = ...
def log_maintenance_run(conn: sqlite3.Connection, command: str, status: str, started: str | None = ..., finished: str | None = ..., duration: float | None = ..., details: dict | None = ...) -> int:
    ...

__all__ = ["log_maintenance_run"]
