"""
This type stub file was generated by pyright.
"""

import sqlite3

"""Journal works fetcher (Crossref) extracted from maintenance.py."""
logger = ...
def fetch_latest_journal_works(conn: sqlite3.Connection, feeds, per_journal: int = ..., timeout: int = ..., delay: float = ..., sort_by: str = ..., date_filter_type: str | None = ..., from_date: str | None = ..., until_date: str | None = ...): # -> int:
    ...

__all__ = ["fetch_latest_journal_works"]
