"""
This type stub file was generated by pyright.
"""

import sqlite3

"""Remove helper extracted from maintenance.py."""
logger = ...
def remove_feed_articles(conn: sqlite3.Connection, feed_keys: list | None = ..., publication_id: str | None = ..., dry_run: bool = ...) -> int:
    ...

__all__ = ["remove_feed_articles"]
