"""
This type stub file was generated by pyright.
"""

"""Compatibility shim for ednews.db.manage_db used by CLI modules.

Pylance/static analyzers can't see the runtime synthesis of
``ednews.db.manage_db`` performed in ``ednews.db.__init__``. Create a
lightweight shim that re-exports the maintenance and migrations helpers so
imports like ``from ednews.db import manage_db`` resolve statically.

This module intentionally avoids heavyweight imports at top-level to keep
startup cheap; it re-exports names from sibling modules.
"""
__all__ = ["init_db", "create_combined_view", "sync_publications_from_feeds", "sync_articles_from_items", "fetch_latest_journal_works", "vacuum_db", "log_maintenance_run", "cleanup_empty_articles", "cleanup_filtered_titles", "remove_filtered_titles", "rematch_publication_dois", "remove_feed_articles", "migrate_db", "migrate_add_items_url_hash"]
remove_filtered_titles = ...
