"""
This type stub file was generated by pyright.
"""

"""Schema migrations for ednews DB (extracted from manage_db)."""
logger = ...
def create_combined_view(conn): # -> None:
    ...

def migrate_add_items_url_hash(conn): # -> dict[str, Any]:
    ...

def migrate_db(conn): # -> bool:
    ...

