"""
This type stub file was generated by pyright.
"""

"""Publication helpers split from ednews.db.__init__."""
logger = ...
def upsert_publication(conn, feed_id: str | None, publication_id: str | None, feed_title: str | None, issn: str | None): # -> bool:
    ...

def sync_publications_from_feeds(conn, feeds_list) -> int:
    ...

__all__ = ["upsert_publication", "sync_publications_from_feeds"]
