"""
This type stub file was generated by pyright.
"""

import sqlite3

"""Schema and view creation helpers (extracted from manage_db)."""
logger = ...
def init_db(conn: sqlite3.Connection): # -> None:
    """Initialize the database schema and create required tables/views."""
    ...

def create_combined_view(conn: sqlite3.Connection): # -> None:
    ...

