"""
This type stub file was generated by pyright.
"""

from pathlib import Path

"""Build utilities for ed-news.

This module contains helpers to render the static site from templates,
copy static assets and the SQLite database, and read feed/planet
configuration used to assemble the site.
"""
MODEL_NAME = ...
BUILD_DIR = ...
PKG_DIR = ...
TEMPLATES_DIR = ...
STATIC_DIR = ...
PLANET_FILE = ...
DB_FILE = ...
logger = ...
def item_has_content(item: dict) -> bool:
    """Return True if the given feed/article-like item has any usable content.

    We treat an item as having content if at least one of title, link or
    content/abstract is present and non-empty after stripping.
    """
    ...

def get_similar_articles_by_doi(conn, doi, top_n=..., model=..., store_if_missing: bool = ...): # -> list[Any]:
    """Return a list of similar articles for the given DOI using stored embeddings.

    The function looks up the article by DOI, retrieves its embedding from the
    ``articles_vec`` virtual table and performs a cosine-distance nearest-
    neighbors query using sqlite-vec.

    Args:
        conn (sqlite3.Connection): Open SQLite connection with sqlite-vec loaded.
        doi (str): DOI of the target article to find similarities for.
        top_n (int): Maximum number of similar articles to return.
        model (str): Embedding model name (unused here, kept for API compatibility).
        store_if_missing (bool): Whether to attempt to store a generated embedding
            if missing (not implemented here; present for compatibility).

    Returns:
        list: A list of dicts with keys: 'doi', 'title', 'abstract', 'distance'.
    """
    ...

def read_planet(planet_path: Path): # -> dict[str, Any]:
    """Read a planet.ini-style file and return site metadata and feeds.

    The function wraps the planet file with a ``[global]`` section so that
    :class:`configparser.ConfigParser` can parse top-level key/value pairs.

    Args:
        planet_path (pathlib.Path): Path to the planet.ini file to read.

    Returns:
        dict: A mapping with keys ``title`` and ``feeds``. ``feeds`` is a list
            of feed descriptor dicts with keys ``id``, ``title``, ``link`` and
            ``feed``.
    """
    ...

def render_templates(context, out_dir: Path): # -> None:
    """Render Jinja2 templates from the templates directory into ``out_dir``.

    Args:
        context (dict): Template context mapping used when rendering templates.
        out_dir (pathlib.Path): Output directory where rendered templates will
            be written.
    """
    ...

def copy_static(out_dir: Path): # -> None:
    """Copy the project's ``static/`` directory into the build output.

    If the destination exists it will be removed before copying.

    Args:
        out_dir (pathlib.Path): Destination directory for static assets.
    """
    ...

def build(out_dir: Path = ...): # -> None:
    """High-level build function to render the static site.

    The function collects site metadata, loads recent articles from the
    configured DB (by default the most recent 20 articles, see
    :func:`read_articles`), computes similar-article suggestions, renders
    templates, copies static assets and the DB into the output directory.

    Important behaviour: the build always requests the most recent 20
    articles. When more than 20 articles share the same published DATE as the
    20th most recent article, all articles with that DATE are included so the
    site doesn't arbitrarily truncate a day's publications.

    Args:
        out_dir (pathlib.Path): Destination directory for the built static site.
    """
    ...

def read_articles(db_path: Path, limit: int = ..., days: int | None = ..., publications: int | None = ...): # -> list[Any]:
    """Read recent articles from the ``combined_articles`` view in the DB.

    The function supports several retrieval modes:
    * If ``publications`` is provided, returns all articles from the latest
      N publications (one date per publication).
    * Else if ``days`` is provided, returns articles whose ``DATE(published)``
      is in the latest ``days`` distinct dates.
    * Otherwise returns the most recent ``limit`` articles. When using the
      fallback ``limit`` mode (i.e. ``publications`` and ``days`` are not
      provided), the function will expand the selection so that if the Nth
      most recent article (ordered by ``published`` desc) shares its
      DATE(published) with additional articles, those articles are also
      included. This prevents arbitrarily truncating all articles published
      on the same date as the Nth article.

    Args:
        db_path (pathlib.Path): Path to the SQLite database file.
        limit (int): Fallback limit for the number of articles to return.
        days (int | None): Optional number of distinct recent dates to include.
        publications (int | None): Optional number of latest publications to include.

    Returns:
        list[dict]: A list of article dictionaries containing ``title``, ``doi``,
            ``link``, ``feed_title``, ``content``, ``published`` (short date
            string), and ``raw`` (original DB row).
    """
    ...

def read_news_headlines(db_path: Path, limit: int | None = ...): # -> list[Any]:
    """Read the most recent news headlines from the `headlines` table.

    Returns a list of dicts with keys: title, link, text, published (short string).
    """
    ...

def export_db_parquet(out_dir: Path, tables: list | None = ...): # -> None:
    """Export selected tables from the configured SQLite DB into Parquet files

    Uses DuckDB's sqlite extension to read directly from the SQLite
    database file and writes each table to ``out_dir/db/{table}.parquet``.

    Args:
        out_dir (pathlib.Path): Base output directory (typically the build dir).
        tables (list[str] | None): List of table names to export. If omitted,
            exports the default set: articles, items, publications, articles_vec.
    """
    ...

