"""
This type stub file was generated by pyright.
"""

"""Crossref integration helpers for ed-news.

This module contains utilities to lookup DOIs by title, fetch Crossref
metadata (preferring the JSON REST API and falling back to Unixref XML),
and normalize date strings returned by Crossref. Functions in this module
are used by feed processing and ScienceDirect enrichment helpers.
"""
logger = ...
_query_crossref_doi_by_title_cached = ...
def query_crossref_doi_by_title(*args, **kwargs) -> str | None:
    """Compatibility wrapper for Crossref title lookup.

    Accepts the legacy signature either as positional arguments
        (title, preferred_publication_id=None, timeout=8)
    or as keywords. Normalizes inputs and calls the cached implementation.
    """
    ...

def fetch_crossref_metadata(*args, **kwargs) -> dict | None:
    """Compatibility wrapper for fetching Crossref metadata.

    Accepts either the legacy positional signature:
        (doi, timeout=10, conn=None, force=False)
    or keyword arguments. Normalizes the inputs and delegates to the
    internal implementation.
    """
    ...

def normalize_crossref_datetime(dt_str: str) -> str | None:
    """Normalize a Crossref-derived datetime or date string to ISO format.

    Accepts partial date strings such as 'YYYY' or 'YYYY-MM' and returns them
    unchanged. For full datetimes attempts to parse via datetime.fromisoformat
    and returns an ISO 8601 string including timezone information when possible.
    """
    ...

