"""
This type stub file was generated by pyright.
"""

import sqlite3
from typing import List, Optional, Tuple

"""Embedding utilities for ed-news.

This module provides a small, test-friendly wrapper around sqlite-vec and
the local nomic embed API. It supports creating named virtual tables (for
articles and headlines), generating embeddings for arbitrary (id, text)
tuples and querying nearest neighbours using cosine distance.
"""
DATABASE_NAME = ...
MODEL_NAME = ...
def upsert_embeddings(conn: sqlite3.Connection, table_name: str, items: List[Tuple[int, str]], model: Optional[str] = ..., batch_size: int = ...) -> int:
    """Generate embeddings for (id, text) items and upsert into named vec table.

    Returns the number of embeddings written.
    """
    ...

def create_articles_vec(conn: sqlite3.Connection, dim: int = ...): # -> None:
    ...

def create_headlines_vec(conn: sqlite3.Connection, dim: int = ...): # -> None:
    ...

def generate_and_insert_article_embeddings(conn: sqlite3.Connection, model: Optional[str] = ..., batch_size: int = ..., force: bool = ...): # -> int:
    """Generate and insert embeddings for articles.

    If force is False (default), only articles missing embeddings are processed.
    If force is True, all eligible articles are re-embedded.
    """
    ...

def generate_and_insert_embeddings_local(conn: sqlite3.Connection, model: Optional[str] = ..., batch_size: int = ...): # -> int:
    """Compatibility wrapper for the older API name used by main.py.

    Historically the CLI used generate_and_insert_embeddings_local. Keep a
    wrapper that delegates to the current article embedding generator.
    """
    ...

def create_database(conn: sqlite3.Connection): # -> None:
    """Compatibility wrapper: create the `articles_vec` virtual table if possible."""
    ...

def generate_and_insert_embeddings_for_ids(conn: sqlite3.Connection, ids: List[int], model: Optional[str] = ...) -> int:
    """Compatibility wrapper: generate embeddings for the provided article ids.

    Returns the number of embeddings written.
    """
    ...

def generate_and_insert_headline_embeddings(conn: sqlite3.Connection, model: Optional[str] = ..., batch_size: int = ...) -> int:
    """Generate and insert embeddings for news headlines by concatenating title and text.

    Embeddings are stored in `headlines_vec` with rowid equal to `headlines.id`.
    """
    ...

def find_similar_headlines_by_rowid(conn: sqlite3.Connection, rowid: int, top_n: int = ...): # -> list[Any]:
    ...

