"""
This type stub file was generated by pyright.
"""

from typing import Any

"""HTTP helpers with retry/backoff/jitter and simple metrics for ed-news.

This module centralizes logic for performing HTTP GET requests with
configurable timeouts, retries, and exponential backoff. It exposes
convenience helpers for JSON and text responses and records simple
metrics counters that can be logged by callers.
"""
logger = ...
metrics = ...
def request_with_retries(method: str, url: str, params=..., headers=..., timeout=..., retries: int = ..., backoff: float = ..., status_forcelist=..., requests_module=...): # -> Response | None:
    """Perform an HTTP request with simple retry/backoff/jitter.

    Args:
        method: HTTP method (only 'GET' supported currently)
        url: URL to request
        params: optional query params
        headers: optional headers
        timeout: tuple (connect, read) or single float read timeout
        retries: number of retry attempts (total attempts = retries+1)
        backoff: base backoff factor for exponential backoff
        status_forcelist: iterable of status codes considered retryable

    Returns:
        requests.Response on success

    Raises:
        Exception from last failed attempt when retries exhausted
    """
    ...

def get_json(url: str, params=..., headers=..., timeout=..., retries: int = ..., backoff: float = ..., status_forcelist=..., requests_module=...) -> Any:
    ...

def get_text(url: str, params=..., headers=..., timeout=..., retries: int = ..., backoff: float = ..., status_forcelist=..., requests_module=...) -> str:
    ...

