"""
This type stub file was generated by pyright.
"""

import sqlite3
from pathlib import Path
from typing import Any, Dict, List

"""News aggregator for ad-hoc site processors and RSS feeds.

This module loads `news.json`, and for each configured site either
parses an RSS/Atom feed or delegates to a site-specific processor
that extracts headlines from HTML.

Only lightweight functionality is implemented: fetch, normalize,
and return a list of headline dicts with keys: title, link,
summary, and published (string when available).
"""
CONFIG_PATH = ...
def load_config(path: Path | str | None = ...) -> Dict:
    """Load the news configuration JSON.

    Args:
        path: Optional path to a JSON file. Defaults to `news.json` in cwd.

    Returns:
        Parsed JSON as a dict.
    """
    ...

PROCESSORS = ...
FEED_PROCESSORS = ...
def fetch_site(session: Any, site_cfg: Dict) -> List[Dict]:
    """Fetch a single site configuration and return normalized headline dicts.

    site_cfg is expected to contain keys: title, link, feed, processor.
    If `feed` is provided and non-empty, parse it with feedparser.
    If `processor` is provided and matches a function in PROCESSORS,
    fetch the HTML and run the processor.
    """
    ...

def fetch_all(session: object | None = ..., cfg_path: str | Path | None = ..., conn: sqlite3.Connection | None = ...) -> Dict[str, List[Dict]]:
    """Load configuration and fetch headlines for all configured sites.

    Returns a mapping from site key to list of headline dicts.
    """
    ...

