---
kind: pipeline
type: docker
name: update ed-news website

steps:
    - name: restore cache
      image: meltwater/drone-cache:dev
      pull: true
      settings:
        backend: "filesystem"
        restore: true
        cache_key: "volume"
        archive_format: "gzip"
        mount:
          - 'cache'
      volumes:
      - name: cache
        path: /tmp/cache

    - name: fetch feeds
      image: ghcr.io/astral-sh/uv:debian
      commands:
        - apt update; apt install -y cmake
        - mkdir -p cache
        - ln -sf cache/ednews.db ednews.db
        - uv venv --python 3.14
        - uv sync
        - uv run python fetch.py --enrich-sciencedirect
        - uv run python calculate_vectors.py
        - uv run python build.py

    - name: rebuild cache
      image: meltwater/drone-cache:dev
      pull: true
      settings:
        backend: "filesystem"
        rebuild: true
        cache_key: "volume"
        archive_format: "gzip"
        mount:
          - 'cache'
      volumes:
      - name: cache
        path: /tmp/cache

    - name: update server
      image: drillster/drone-rsync
      volumes:
        - name: www_dir
          path: /www
      commands:
        - rsync -rltvzc --delete --omit-dir-times --no-o --no-g build/ /www/

    - name: invalidate-cloudflare-cache
      image: jetrails/drone-cloudflare-caching
      settings:
          api_token:
              from_secret: cloudflare_token
          zone_identifier:
              from_secret: cloudflare_zone_identifier
          action: purge_everything

volumes:
    - name: cache
      host:
        path: /data/drone/cache
    - name: www_dir
      host:
        path: /data/www/ed-news
...
