---
kind: pipeline
type: docker
name: update ed-news website

steps:
    - name: restore cache
      image: meltwater/drone-cache:dev
      pull: true
      settings:
        backend: "filesystem"
        restore: true
        cache_key: "volume"
        archive_format: "gzip"
        mount:
          - 'cache'
      volumes:
      - name: cache
        path: /tmp/cache

    - name: fetch feeds
      image: ebardelli/ed-news
      commands:
        - pluto update --dbname=cache/ed-news.db
        - sqlite3 cache/ed-news.db 'UPDATE "items" SET "published" = "created_at" WHERE "published" > CURRENT_TIMESTAMP;'
        - pluto merge --dbname=cache/ed-news.db --output=ed-news --template umich

    - name: rebuild cache
      image: meltwater/drone-cache:dev
      pull: true
      settings:
        backend: "filesystem"
        rebuild: true
        cache_key: "volume"
        archive_format: "gzip"
        mount:
          - 'cache'
      volumes:
      - name: cache
        path: /tmp/cache

    - name: update netlify
      image: pacbard/drone-netlify
      settings:
        path: ./ed-news/
        site_id: 
          from_secret: netlify_site_id
      environment:
        NETLIFY_TOKEN:
          from_secret: netlify_token
    
    - name: update GH Pages
      image: plugins/gh-pages
      settings:
        username:
          from_secret: gh_username
        password:
          from_secret: gh_token
        pages_directory: ed-news/

    - name: update server
      image: drillster/drone-rsync
      volumes:
        - name: www_dir
          path: /www
      commands:
        - rsync -rltvzc --delete --omit-dir-times --no-o --no-g ed-news/ /www/

volumes:
    - name: cache
      host:
        path: /data/drone/cache
    - name: www_dir
      host:
        path: /data/www/ed-news
...
