---
kind: pipeline
type: docker
name: update ed-news website

steps:
    - name: restore cache
      image: alpine 
      volumes:
        - name: cache
          path: /cache
      commands:
        - cp /cache/ed-news.db .

    - name: fetch feeds
      image: ebardelli/ed-news
      commands:
        - pluto update --dbname=ed-news.db
        - sqlite3 ed-news.db 'UPDATE "items" SET "published" = "created_at" WHERE "published" > CURRENT_TIMESTAMP;'
        - pluto merge --dbname=ed-news.db --output=ed-news --template umich

    - name: cache database
      image: alpine
      volumes:
        - name: cache
          path: /cache
      commands:
        - cp ed-news.db /cache/

    - name: update netlify
      image: pacbard/drone-netlify
      settings:
        path: ./ed-news/
        site_id: 
          from_secret: netlify_site_id
      environment:
        NETLIFY_TOKEN:
          from_secret: netlify_token
    
    - name: update GH Pages
      image: plugins/gh-pages
      settings:
        username:
          from_secret: gh_username
        password:
          from_secret: gh_token
        pages_directory: ed-news/

volumes:
    - name: cache
      host:
        path: /data/drone/cache
...
