---
kind: pipeline
type: docker
name: update ed-news website

steps:
    - name: restore cache
      image: meltwater/drone-cache:dev
      pull: true
      settings:
        backend: "filesystem"
        restore: true
        cache_key: "volume"
        archive_format: "gzip"
        mount:
          - 'cache'
      volumes:
      - name: cache
        path: /tmp/cache

    - name: fetch feeds
      image: python:3.14-slim
      commands:
        - apt-get update && apt-get install -y --no-install-recommends curl ca-certificates
        - curl -LsSf https://astral.sh/uv/install.sh | sh
        - source $HOME/.local/bin/env
        - mkdir -p cache
        - ln -sf cache/ednews.db ednews.db
        - uv venv --python 3.14
        - uv sync
        - uv run python fetch.py
        - uv run python build.py

    - name: rebuild cache
      image: meltwater/drone-cache:dev
      pull: true
      settings:
        backend: "filesystem"
        rebuild: true
        cache_key: "volume"
        archive_format: "gzip"
        mount:
          - 'cache'
      volumes:
      - name: cache
        path: /tmp/cache

    - name: update server
      image: drillster/drone-rsync
      volumes:
        - name: www_dir
          path: /www
      commands:
        - rsync -rltvzc --delete --omit-dir-times --no-o --no-g build/ /www/

volumes:
    - name: cache
      host:
        path: /data/drone/cache
    - name: www_dir
      host:
        path: /data/www/ed-news
...
