---
kind: pipeline
type: docker
name: update ed-news website

# platform:
#   os: linux
#   arch: arm64

steps:
    - name: restore venv cache
      image: meltwater/drone-cache:dev
      pull: true
      settings:
        backend: "filesystem"
        restore: true
        cache_key: "volume"
        archive_format: "gzip"
        mount:
          - 'venv'
      volumes:
      - name: venv
        path: /tmp/venv

    - name: restore db cache
      image: meltwater/drone-cache:dev
      pull: true
      settings:
        backend: "filesystem"
        restore: true
        cache_key: "volume"
        archive_format: "gzip"
        mount:
          - 'cache'
      volumes:
      - name: cache
        path: /tmp/cache

    - name: fetch feeds
      image: ghcr.io/astral-sh/uv:debian
      commands:
        - echo "Creating db cache directory if it doesn't exist..."
        - mkdir -p cache
        - echo "Checking if ednews.db exists in cache..."
        - '[ -f cache/ednews.db ] || (echo "ednews.db not found, creating an empty file..." && touch cache/ednews.db)'
        - echo "Creating symbolic link for ednews.db..."
        - ln -sf cache/ednews.db ednews.db
        - uv venv --python 3.13
        - uv sync
        - uv run python main.py fetch
        - uv run python main.py issn-lookup
        - uv run python main.py enrich-crossref --batch 100
        - uv run python main.py embed
        - uv run python main.py build

    - name: rebuild db cache
      image: meltwater/drone-cache:dev
      pull: true
      settings:
        backend: "filesystem"
        rebuild: true
        cache_key: "volume"
        archive_format: "gzip"
        mount:
          - 'cache'
      volumes:
      - name: cache
        path: /tmp/cache

    - name: rebuild venv cache
      image: meltwater/drone-cache:dev
      pull: true
      settings:
        backend: "filesystem"
        rebuild: true
        cache_key: "volume"
        archive_format: "gzip"
        mount:
          - 'venv'
      volumes:
      - name: venv
        path: /tmp/venv

    - name: update server
      image: drillster/drone-rsync
      volumes:
        - name: www_dir
          path: /www
      commands:
        - rsync -rltvzc --delete --omit-dir-times --no-o --no-g build/ /www/

    - name: invalidate-cloudflare-cache
      image: jetrails/drone-cloudflare-caching
      settings:
          api_token:
              from_secret: cloudflare_token
          zone_identifier:
              from_secret: cloudflare_zone_identifier
          action: purge_everything

volumes:
    - name: cache
      host:
        path: /data/drone/cache
    - name: venv
      host:
        path: /data/drone/.venv
    - name: www_dir
      host:
        path: /data/www/ed-news
...
