"""
This type stub file was generated by pyright.
"""

from .fcmat import fcmat_processor
from .pressdemocrat import pd_education_feed_processor
from .sciencedirect import enrich_sciencedirect, find_sciencedirect_items_missing_metadata, sciencedirect_feed_processor, sciencedirect_postprocessor_db
from .crossref import crossref_enricher_processor, crossref_postprocessor_db
from .edworkingpapers import edworkingpapers_feed_processor, edworkingpapers_postprocessor_db, edworkingpapers_processor
from .rss import rss_preprocessor
from typing import Any, Callable

"""Collection of site/feed processors for ednews.

This package aggregates site-specific preprocessors and postprocessors
and exposes a stable set of symbols used by the rest of the application.
Keep this module small and single-purpose to avoid accidental
redefinitions that can hide processor implementations.
"""
def resolve_postprocessor(proc_config: Any, preferred_proc_name: str | None = ...) -> Callable | None:
    """Resolve a DB-level postprocessor callable.

    Resolution order:
    - If proc_config is set for a feed, try its 'post' name(s) or string(s) first.
    - Next, try the preferred_proc_name (typically from CLI --processor).
    - Finally, attempt to return the `crossref_postprocessor_db` if available.

    `proc_config` may be a string, a list/tuple of strings, or a dict with a
    `post` key. This helper will attempt to lookup `<name>_postprocessor_db`
    in this package first, then attempt to import the module by name and
    look for the same symbol as a fallback.
    """
    ...

crossref_feed_processor = ...
sciencedirect_preprocessor = ...
edworkingpapers_preprocessor = ...
pd_education_preprocessor = ...
fcmat_preprocessor = ...
sciencedirect_postprocessor_db = ...
crossref_postprocessor = ...
crossref_postprocessor_db = ...
__all__ = ["fcmat_processor", "pd_education_feed_processor", "find_sciencedirect_items_missing_metadata", "enrich_sciencedirect", "sciencedirect_feed_processor", "crossref_enricher_processor", "edworkingpapers_processor", "edworkingpapers_feed_processor", "edworkingpapers_postprocessor_db", "sciencedirect_postprocessor_db", "crossref_postprocessor_db", "rss_preprocessor", "sciencedirect_preprocessor", "edworkingpapers_preprocessor", "pd_education_preprocessor", "fcmat_preprocessor"]
