"""
This type stub file was generated by pyright.
"""

from typing import List

"""Processor adapter that enriches feed entries using ednews.crossref helpers.

This module exposes an enricher-style processor named
`crossref_enricher_processor(entries, session=None, publication_id=None, issn=None)`
which accepts a list of feed entry dicts and returns an enriched list.
"""
logger = ...
def crossref_enricher_processor(entries: List[dict], session=..., publication_id: str | None = ..., issn: str | None = ...) -> List[dict]:
    """Enrich a list of feed entries using Crossref metadata.

    For each entry, attempt to determine a DOI (from the entry fields or
    via a Crossref title lookup) and fetch Crossref metadata. When found,
    merge authors, abstract, published and raw crossref payload into the
    entry dict under keys 'doi', 'authors', 'abstract', 'crossref_raw', 'published'.
    """
    ...

def crossref_postprocessor_db(conn, feed_key: str, entries, session=..., publication_id: str | None = ..., issn: str | None = ..., force: bool = ..., check_fields: list[str] | None = ...): # -> int:
    """DB-level postprocessor: for each entry, determine DOI and upsert article rows.

    This function mirrors the behavior of `crossref_enricher_processor` but
    performs DB writes using `ednews.db` helpers so that articles and items
    are persisted with Crossref metadata attached.
    """
    ...

