"""
This type stub file was generated by pyright.
"""

from typing import Dict, List

def edworkingpapers_processor(html: str, base_url: str | None = ..., publication_id: str | None = ...) -> List[Dict]:
    """Parse EdWorkingPapers listing page HTML and extract paper items.

    Returns a list of dicts with keys: title, link, summary, published.
    """
    ...

def edworkingpapers_feed_processor(session, feed_url: str, publication_id: str | None = ..., issn: str | None = ...): # -> dict[str, Any] | List[Dict[Any, Any]]:
    """Feed-style processor used by the fetcher.

    Accepts a requests-like session and a URL, fetches the HTML and returns
    a dict with keys similar to other feed processors: key, title, url,
    publication_id, error, entries (list of item dicts).
    """
    ...

def edworkingpapers_postprocessor_db(conn, feed_key: str, entries, session=..., publication_id: str | None = ..., issn: str | None = ..., force: bool = ..., check_fields: list | None = ...): # -> int:
    """DB-level postprocessor for EdWorkingPapers.

    For each entry, fetch the article page (e.g., https://edworkingpapers.com/ai25-1322),
    extract DOI, title, authors, abstract, published, and upsert into `articles`.
    Also attach the DOI to corresponding rows in `items` when found.
    Returns the number of articles upserted.
    """
    ...

