"""
This type stub file was generated by pyright.
"""

from typing import Dict, List

def fcmat_processor(html: str, base_url: str | None = ...) -> List[Dict]:
    """Parse FCMAT headlines page HTML and extract headline items.

    Returns a list of dicts: title, link, summary, published.
    """
    ...

def fcmat_preprocessor(session_or_html, base_url: str | None = ...): # -> List[Dict[Any, Any]] | list[Any]:
    ...

