"""
This type stub file was generated by pyright.
"""

import requests
from typing import Dict, List

def pd_education_feed_processor(session: requests.Session, feed_url: str) -> List[Dict]:
    """Fetch the Press Democrat feed and keep only Local News items.

    Args:
        session: requests.Session to use for fetching.
        feed_url: URL of the RSS/Atom feed.

    Returns:
        List of normalized headline dicts (title, link, summary, published)
        containing only items categorized as Local News.
    """
    ...

def pd_education_preprocessor(session, feed_url: str, publication_id: str | None = ..., issn: str | None = ...): # -> List[Dict[Any, Any]] | list[Any]:
    ...

