"""
This type stub file was generated by pyright.
"""

from typing import List

"""Generic RSS/Atom preprocessor wrapper.

This module exposes `rss_preprocessor(session, feed_url, publication_id=None, issn=None)`
which delegates to `ednews.feeds.fetch_feed` and returns the `entries` list so it
can be used as a drop-in preprocessor for RSS/Atom feeds.
"""
def rss_preprocessor(session, feed_url: str, publication_id: str | None = ..., issn: str | None = ...) -> List[dict]:
    """Fetch an RSS/Atom feed and return the parsed entries list.

    This simply wraps `ednews.feeds.fetch_feed` and returns the `entries` list
    to match preprocessor semantics used by the CLI.
    """
    ...

