"""
This type stub file was generated by pyright.
"""

import sqlite3
from typing import List

"""Helpers specific to ScienceDirect items.

Provides utilities to find ScienceDirect-hosted items in the DB and to
attempt enrichment by resolving DOIs and fetching Crossref metadata.
"""
logger = ...
def find_sciencedirect_items_missing_metadata(conn: sqlite3.Connection, limit: int | None = ...) -> List[dict]:
    """Return ScienceDirect items from `items` joining articles where available.

    This helper selects rows from `items` whose link contains 'sciencedirect.com'
    and returns a list of dicts describing each candidate for enrichment.
    """
    ...

def enrich_sciencedirect(conn: sqlite3.Connection, limit: int | None = ..., apply: bool = ..., delay: float = ...) -> int:
    """Enrich ScienceDirect items by attempting to resolve DOIs and Crossref metadata.

    If `apply` is False this function performs a dry-run and logs actions it
    would take. When `apply` is True it will insert or update article rows
    accordingly and commit changes.
    """
    ...

def sciencedirect_feed_processor(session, feed_url: str, publication_id: str | None = ..., issn: str | None = ...): # -> list[Any]:
    """Fetch a ScienceDirect RSS/Atom feed and augment entries with DOI when possible.

    This behaves like a feed fetcher: it returns a list of entry dicts similar
    to what `feeds.fetch_feed` returns in its `entries` list so callers can
    pass the result to `ednews.feeds.save_entries` unchanged.

    The processor attempts a CrossRef title->DOI lookup for items whose link
    contains 'sciencedirect.com' and which do not already include a DOI.
    If a DOI is found, the returned entry will include a top-level 'doi' key
    so the downstream `save_entries` flow can attach and upsert articles.
    """
    ...

def sciencedirect_preprocessor(session, feed_url: str, publication_id: str | None = ..., issn: str | None = ...): # -> list[Any]:
    ...

def sciencedirect_postprocessor_db(conn, feed_key: str, entries, session=..., publication_id: str | None = ..., issn: str | None = ...): # -> int:
    """DB-level postprocessor that processes the provided entries.

    For each entry, attempt to determine a DOI (from the entry, via feed helpers,
    or via a Crossref title lookup). When a DOI is found it will fetch Crossref
    metadata (when needed), upsert an articles row and attach the DOI to the
    corresponding items row(s) for this feed.

    Returns the number of articles upserted/updated.
    """
    ...

