"""
This type stub file was generated by pyright.
"""

import argparse
import logging
from datetime import date
from typing import Any
from .fetch import cmd_fetch
from .build import cmd_build
from .embed import cmd_embed
from .db_init import cmd_db_init
from .issn_lookup import cmd_issn_lookup
from .headlines import cmd_headlines
from .manage_db import cmd_manage_db_cleanup, cmd_manage_db_cleanup_filtered_title, cmd_manage_db_migrate, cmd_manage_db_rematch, cmd_manage_db_remove_feed_articles, cmd_manage_db_run_all, cmd_manage_db_sync_publications, cmd_manage_db_vacuum
from .serve import cmd_serve
from .postprocess import cmd_postprocess
from .common import normalize_cli_date

"""Package-level CLI entrypoint for ed-news.

This module wires subcommands implemented in separate modules under
`ednews.cli` into a single `run()` function so the top-level
`main.py` can remain a thin wrapper.
"""
logger = ...
def run() -> None:
    """Entrypoint for the ednews CLI.

    Parses command-line arguments and dispatches to the appropriate
    `cmd_*` handler functions implemented in submodules.
    """
    ...

__all__ = ["run", "normalize_cli_date"]
