"""
This type stub file was generated by pyright.
"""

from typing import Any

def cmd_build(args: Any) -> None:
    """Render the static site into the output directory.

    Args:
        args: argparse namespace with optional .out_dir attribute.
    """
    ...

