"""
This type stub file was generated by pyright.
"""

import sqlite3
import requests
from typing import Any, Dict, Optional, Tuple

"""Shared helpers for ednews CLI subcommand modules.

Provide small utilities to centralize common operations like creating a
DB connection, creating a requests session, and normalizing CLI dates.
"""
def get_conn() -> sqlite3.Connection:
    """Return a new sqlite3 connection to the configured DB path.

    Returns:
        sqlite3.Connection: new DB connection to `config.DB_PATH`.
    """
    ...

def get_session() -> requests.Session:
    """Create and return a new requests.Session for HTTP requests."""
    ...

def normalize_cli_date(s: Optional[str]) -> Optional[str]:
    """Normalize CLI date inputs for issn-lookup and similar commands.

    - Preserve fragments like 'YYYY', 'YYYY-MM', 'YYYY-MM-DD'.
    - If given a datetime-like string with 'T' and no timezone, treat it as
      UTC and return an ISO-formatted timezone-aware string.
    - Otherwise return the trimmed input.
    """
    ...

def start_maintenance_run(conn: sqlite3.Connection, name: str, meta: Optional[Dict[str, Any]] = ...) -> Tuple[Optional[str], Optional[int]]:
    """Log a maintenance run as started and return (started_iso, run_id).

    This is a thin helper that calls `ednews.db.manage_db.log_maintenance_run`
    if available. It never raises; failures are swallowed and (started, None)
    are returned so callers can proceed.
    """
    ...

def finalize_maintenance_run(conn: sqlite3.Connection, name: str, run_id: Optional[int], started: Optional[str], status: str, details: Optional[Dict[str, Any]] = ...) -> None:
    """Finalize a maintenance run log entry.

    Safe to call even if `start_maintenance_run` returned a None run_id.
    """
    ...

