"""
This type stub file was generated by pyright.
"""

from typing import Any

logger = ...
def cmd_fetch(args: Any) -> None:
    """Fetch configured article feeds and/or news headlines and persist them.

    Args:
        args: argparse namespace with .articles and .headlines boolean flags.
    """
    ...

