"""
This type stub file was generated by pyright.
"""

from typing import Any

logger = ...
def cmd_headlines(args: Any) -> None:
    """Fetch configured news sites and optionally persist or write to JSON.

    Args:
        args: argparse namespace with .out and .no_persist
    """
    ...

