"""
This type stub file was generated by pyright.
"""

from typing import Any

logger = ...
def cmd_postprocess(args: Any) -> None:
    """Run a DB-level postprocessor for configured feeds or a specific feed list.

    Args:
        args: argparse namespace with optional .processor, optional .feed, .only_missing, .missing_field, .force, .check_fields
    """
    ...

