"""
This type stub file was generated by pyright.
"""

from typing import Any

def cmd_serve(args: Any) -> None:
    """Serve the built static site directory over HTTP for local preview.

    Args:
        args: argparse namespace with .host, .port, .directory
    """
    ...

