"""Minimal stub for bs4 (BeautifulSoup) used in processors."""
from typing import Any, Iterable, Optional


class Tag:
    def select_one(self, selector: str) -> Optional["Tag"]: ...

    def select(self, selector: str) -> list["Tag"]: ...

    def get_text(self, separator: Optional[str] = ..., strip: bool = ...) -> str: ...

    @property
    def title(self) -> Optional["Tag"]: ...
    def get(self, name: str, default: Any = ...) -> Any: ...
    def find_parent(self, *args: Any, **kwargs: Any) -> Optional["Tag"]: ...
    def find_next_sibling(self, *args: Any, **kwargs: Any) -> Optional["Tag"]: ...
    @property
    def string(self) -> Optional[str]: ...


class BeautifulSoup(Tag):
    def __init__(self, markup: str, features: str = ...) -> None: ...

    def find(self, *args: Any, **kwargs: Any) -> Any: ...

    def find_all(self, *args: Any, **kwargs: Any) -> list[Any]: ...
